const data = [
  {
    id: 1,
    patientid: 1,
    andningsfrekvens: 1,
    syremättnad: 1,
    syrgas: 1,
    systolisktblodtryck: 3,
    pulsfrekvens: 2,
    medvetandegrad: 0,
    temperatur: 0,
  },
  {
    id: 2,
    patientid: 1,
    andningsfrekvens: 1,
    syremättnad: 2,
    syrgas: 1,
    systolisktblodtryck: 3,
    pulsfrekvens: 2,
    medvetandegrad: 0,
    temperatur: 0,
  },
  {
    id: 3,
    patientid: 2,
    andningsfrekvens: 0,
    syremättnad: 1,
    syrgas: 1,
    systolisktblodtryck: 0,
    pulsfrekvens: 0,
    medvetandegrad: 0,
    temperatur: 1,
  },
  {
    id: 4,
    patientid: 2,
    andningsfrekvens: 0,
    syremättnad: 0,
    syrgas: 1,
    systolisktblodtryck: 0,
    pulsfrekvens: 0,
    medvetandegrad: 0,
    temperatur: 1,
  },
  {
    id: 5,
    patientid: 2,
    andningsfrekvens: 0,
    syremättnad: 1,
    syrgas: 0,
    systolisktblodtryck: 0,
    pulsfrekvens: 0,
    medvetandegrad: 0,
    temperatur: 3,
  },
];

export default data;
